/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "good_mux.v:2" *)
module good_mux(i0, i1, sel, out);
  (* src = "good_mux.v:2" *)
  input i0;
  (* src = "good_mux.v:2" *)
  input i1;
  (* src = "good_mux.v:2" *)
  output out;
  (* src = "good_mux.v:2" *)
  input sel;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(i0),
    .A1(i1),
    .S(sel),
    .X(out)
  );
endmodule
