/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module multiple_modules(a, b, c, y);
  input a;
  input b;
  input c;
  wire net1;
  output y;
  sub_module1 u1 (
    .a(a),
    .b(b),
    .y(net1)
  );
  sub_module2 u2 (
    .a(net1),
    .b(c),
    .y(y)
  );
endmodule

module sub_module1(a, b, y);
  input a;
  input b;
  output y;
  assign y = b & a;
endmodule

module sub_module2(a, b, y);
  input a;
  input b;
  output y;
  assign y = b | a;
endmodule
