/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "multiple_modules.v:10" *)
module multiple_modules(a, b, c, y);
  (* src = "multiple_modules.v:10" *)
  input a;
  (* src = "multiple_modules.v:10" *)
  input b;
  (* src = "multiple_modules.v:10" *)
  input c;
  (* src = "multiple_modules.v:11" *)
  wire net1;
  (* src = "multiple_modules.v:10" *)
  output y;
  (* module_not_derived = 32'd1 *)
  (* src = "multiple_modules.v:12" *)
  sub_module1 u1 (
    .a(a),
    .b(b),
    .y(net1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "multiple_modules.v:13" *)
  sub_module2 u2 (
    .a(net1),
    .b(c),
    .y(y)
  );
endmodule

(* src = "multiple_modules.v:5" *)
module sub_module1(a, b, y);
  (* src = "multiple_modules.v:5" *)
  input a;
  (* src = "multiple_modules.v:5" *)
  input b;
  (* src = "multiple_modules.v:5" *)
  output y;
  assign y = b & a;
endmodule

(* src = "multiple_modules.v:1" *)
module sub_module2(a, b, y);
  (* src = "multiple_modules.v:1" *)
  input a;
  (* src = "multiple_modules.v:1" *)
  input b;
  (* src = "multiple_modules.v:1" *)
  output y;
  assign y = b | a;
endmodule
